language: node_js
node_js:
- '6'
before_deploy:
- echo 'before-deploy:'
- npm run build-prod
- echo src
- ls -lR src
- echo dist
- ls -lR dist
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: p8rJwl3RLfSUyngvbZq68UmGFtki7a4/8X4U5TsyZYvPDTIHQMgbLjO9lzx0qbBR0mLGcz59eu4jAEI7SdfDEmkbrJlaOPedXjZJvhRKSWoheYl2e5jhaXItviowajMQn+SlnAQuG9xxOKtYrc0xHy7yaoPVRR2ehxlAWB7p+A35X99isbRYHQO/MxBHssmEprwUh49yEzBOa6ChAfkURSFK0IQPq2FFjTWe1I06sPUjFNIYKlgYJF45mDv67Sl+05hwWIOuWNPQlbYJ4JZrj7OJ7JUQl2Ms+qXOqhMehnFFpUD7UavhAp/HezvSjEQdTAgjXUM+zihu0wmY0QIIYqLRoYiEVr3Bzc5NLiExEv86cPmmmNEgDxBiC+LrKy5FFWy9A756F4G9MXUI8kIMDUHK9EnaPLo6EphuOEbgNxB6CWaIqUbicA+RmmezwsH6DQb7ilbbwR5J9CIkk36YbY29SgGxz5MadqFJu8GgjXqY7MocDDgsMnsJHPwigV+X4H2ywNQJlaSxYiW7J9wlfkfIeifB5lSC6kQiPQDPGwI+fkErpKOeN+GCGcFDfvwdVNvP2BaFnlWpjRgngY7yCJF9FR9WGppZvGypgFoPhQFId0zn+7J+WXc+PDw3bPkWOe5kut9bnYuckSn7hZ57Xr+lNt1S7gzgztFA0OjQ5PE=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
